### ISSUE TITLE
Environment variables docs missing data

### ISSUE THREAD

**Issue by popey** [canonical-websites/docs.snapcraft.io#65]
Working with a developer this week, we found it difficult to find details on where all the $SNAP* and $SNAPCRAFT* environment variables point to.

Googling we found https://github.com/snapcore/snapd/wiki/Environment-Variables and https://snapdocs.labix.org/look-at-this/5368 neither of which are pages linked on the main docs site.

These are important for developers who need to know the defaults of where data is being stored.

**Comment by popey** [comment]
In addition, it's not clear from https://docs.snapcraft.io/commands-and-aliases/3950 or https://docs.snapcraft.io/environment-variables/7983 how the `environment` parameter in `apps` works. 

So for example:-

```
apps:
  myapp:
    command: bin/myapp
    plugs:
      - pulseaudio
    environment:
      "LD_LIBRARY_PATH": "$LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio"
```

Note that we're using an existing variable here, extending it with one variable that gets expanded at build time ($SNAPCRAFT_ARCH_TRIPLET) and another which gets expanded at runtime ($SNAP). This is obscure, but well-used and should be clearly documented.
